volumes:
  pgdata:

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON_URL: http://localhost:8080/openapi.json

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realworld_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      
  # no volume for test container
  test-db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: testpostgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
