http_server:
  port: 8080
  is_swagger_enabled: true
  allowed_origins:
    # swagger ui
    - "http://localhost:8081"
jwt_auth_service:
  # The type of this field, and other secret fields, is set to SecretString in the config struct it loads into.
  # The ConfigLoader will use the SecretParser implementation in the depedency tree to parse fields of this type.
  # Right now this is simply an IdentitySecretParser, but this could be extended to support a wide range of secret management 
  # solutions (e.g. encrypted text, vault, AWS secrets manager, etc.), by implementing the SecretParser interface.
  secret_base_64: "rRLbHa2yFvLTGPEVyJb8mY4wvH//8vBkOHOkyLyg0yI=" # generated via "openssl rand -base64 32"
  token_duration_seconds: 36000
slog:
  level: "DEBUG"
realworld_app_db:
  host: "localhost"
  port: 5432
  username: "postgres"
  # This also has the type SecretString
  password: "password"
  db_name: "realworld_app"
  ssl_mode: "disable"
